### ISSUE TITLE
Maintaining React Native Orientation

### ISSUE THREAD

**Issue by yamill** [yamill/react-native-orientation#162]
Hi all,

Sorry that I haven't been able to keep this project up-to-date. I've been so busy with work. Luckily I had @jevakallio reach out and offered to help keep this repo alive. If anyone else would like to become a collaborator please let me know in this thread below. I think it be good to have another dev who is passionate about this project.

Cheers!
Yamill

**Comment by jevakallio** [comment]
Thanks on all your great work on this project @yamill. Ironically, I'm a bit slammed for a few days now, but will get to reviewing issues and pull requests shortly.

Another maintainer, especially one with deep Android experience, would be much appreciated!

**Comment by simonvaucher** [comment]
Good news!
It's of utter importance to keep this repo alive.
I'd like to help, alas my Android experience is not-that-deep.

**Comment by manask88** [comment]
I can help out here!!. I'm using this library and I had to fork it to be able to keep using in with RN 0.40 in iOS

**Comment by gaguirre** [comment]
@jevakallio Great! I can help with Android ;)
I think a good first step could be making this module compatible with the latest RN version.

**Comment by andrerfneves** [comment]
@yamill can we try and work something out here?

**Comment by jevakallio** [comment]
@andrerfneves I know it's highly ironic that I asked for the maintainer bit, and then haven't done anything with it. Life comes at you fast sometimes.

@andrerfneves what are the most crucial issues (besides the 0.40+ iOS bump) that you think need attention?

**Comment by andrerfneves** [comment]
@jevakallio I completely understand. Just wanting to know if I should fork the repo and add the +0.40 update to the package or if it is going to be done anytime soon. I saw the multiple chats regarding the availability of the maintainer so figured I'd ask if positions were taking?

My most crucial issue is that it doesn't work with RN 0.42 Android, which is the current system I'm in. Is there anything you'd need help with in order to get things going here?

**Comment by jevakallio** [comment]
I'm just now looking to understand what is the best way to do the upgrade with respect to maintaining backwards compatibility, which docs needs to be updated etc. None of the open pull requests seem to take into account the upgrade path.

Is there an open issue or PR for the Android problem @andrerfneves?

**Comment by andrerfneves** [comment]
@jevakallio I mistakenly assumed the 0.40 import changes affected Android as well. I was however able to get it working with the `master` branch on the git repo instead of on npmjs thanks to some other comments.

I am however willing to work on this / docs / code to get the 0.40+ code shipped and new upgrade docs going. Let me know if that's something you want me to look into.

Cheers!

**Comment by manask88** [comment]
@jevakallio right now I think the most pressing issue we should try to fix is support rn >0.40. I myself needed it urgently and had to merge this library. I am willing to help here. I have both iOS and Android experience

**Comment by muratozgul** [comment]
When should we expect the rn >0.40 fix (published to npm)?

**Comment by saidmoya12** [comment]
Is possible create a tag for <= 0.39 react native compatible?

@jevakallio and @yamill I can help you a bit?

**Comment by stoneman1** [comment]
#165 Should work out of the box with old syntax and new

**Comment by yamill** [comment]
@gaguirre 
@colinramsay
@saidmoya12 
@andrerfneves 
@simonvaucher 

Great to hear that all of you would like to help! Are all of you still willing to become contributors?  Please let me know and would be glad to give access to those who **really** can keep this repo alive. I'd like to keep the access at a minimum.

**Comment by andrerfneves** [comment]
@yamill count me in

**Comment by andrerfneves** [comment]
Will definitely start by cleaning up all of these issues!

**Comment by manask88** [comment]
@yamill i'm still willing to become a contributor as well. I'm actively using this library, so it's in my best interest to keep this fully functional!

**Comment by stoneman1** [comment]
@yamill Yes I am in and I can really keep the repo alive.

**Comment by colinramsay** [comment]
@yamill yes, I can certainly help with issue triage if nothing else. Thanks for the response!

**Comment by gaguirre** [comment]
@yamill I can help with Android ;)

**Comment by andrerfneves** [comment]
I think amongst @gaguirre, @colinramsay, @stoneman1 and I we have a solid React Native/Android/iOS team to bring this package back to full compatibility with RN and start an initiative to resolve all outstanding issues. @yamill ultimately it's your decision (as to who and how many contributors) but would love if we can get this sorted out sooner rather than later. Cheers!

**Comment by wellyshen** [comment]
Does the maintain kick off?

**Comment by andrerfneves** [comment]
@wellyshen still waiting to hear from @yamill to actually close this. We need him to grant us `Contributor` access to the repo. It shouldn't take more than 2 minutes. This man must be super busy! I'm all set to start fixing these issues.

**Comment by andrerfneves** [comment]
Hey @yamill, you around to work this out today by any chance?

**Comment by aqnaruto** [comment]
did this support rn>4.0 yet?

**Comment by stoneman1** [comment]
@aqnaruto There is some forks out. Mine fork works at least

**Comment by aqnaruto** [comment]
great!,thanks , i love you @stoneman1

**Comment by yamill** [comment]
Added @andrerfneves @gaguirre @colinramsay @stoneman1 as contributors :)

**Comment by andrerfneves** [comment]
@yamill thanks my man. I'll take a look throughout this week and arrange with these guys to get the ball rolling.
