### ISSUE TITLE
Orientation layout problem

### ISSUE THREAD

**Issue by ajmeraramesh** [yamill/react-native-orientation#50]
Hi,
I am new to react native. I developed a small application using orientation which needs to work with two   layouts for portrait view and landscape view both are different styles layouts. when i open the application in landscape and when i logout through landscape i get no problem in the layout where as when i login in  landscape view and logout in portrait view i get the landscape layout  its not getting the present orientation which i am using when we logout. I get the initial orientation according to that its getting the final view. can some one help me   or suggest me what to do ..

**Comment by andrerfneves** [comment]
@ajmeraramesh in your application entry point, you should use the `getInitialOrientation` method to get the current device's orientation async and then either `lockToPortrait` or `lockToLandscape` according to the return statement. That way your application will always start up the correct way the user's orientation is. Also try and update to latest version as things might have changed since then.
