### ISSUE TITLE
pop can't call lock method well

### ISSUE THREAD

**Issue by L-Jovi** [yamill/react-native-orientation#72]
I do `navigator.push()` and execute `lockToLANDSCAPE` in `componentDidMount` method and I get `LANDSCAPE` orientation.

then I want to `navigator.pop()` and expect back to `PORTRAIT` orientation, so I call `lockToPortrait` after `pop`, it works.

.. but I find that device orientation can't change to `PORTRAIT` if I already put my device in `PORTRAIT` orientation **(`lockToLANDSCAPE` now)** when I prepare to `pop`.

how should I fix it?

thanks for your time.

**Comment by L-Jovi** [comment]
any idea now :)

**Comment by L-Jovi** [comment]
er..  does this smart project continually maintained?

**Comment by andrerfneves** [comment]
@L-Jovi this package just got a couple more collaborators so we're working through the issues. Is this still happening to your application? I believe the package has advanced quite a bit since then, could you test it with the updated version? Please refer to README for detailed instructions to install.
