### ISSUE TITLE
Orientation locking not working

### ISSUE THREAD

**Issue by regentcid434** [yamill/react-native-orientation#76]
I have been using this package for a few months, and it worked well. This week we upgraded from react native 0.24 to 0.27. Now the orientation locking methods are not working. I tried other orientations as well, but none of them worked either. Stepping through it, the function is being called, and no error is being thrown.

```
componentWillMount() {
        console.log(Orientation.getInitialOrientation());
        Orientation.addOrientationListener(this._orientationDidChange);
        if(Device.isTablet){
            Orientation.lockToLandscape();
        }
    }
```

**Comment by Alternhuman** [comment]
Same issue here. It works with 1.16.0.

**Comment by sjchmiela** [comment]
That's because you have to do an extra step of installation, introduced with 1.17.0.

https://github.com/yamill/react-native-orientation#ios

If `Orientation.h` can't be found, add to Your Project Settings — Build Settings — Header Search paths: `$(SRCROOT)/../node_modules/react-native-orientation/iOS` (recursive).

**Comment by regentcid434** [comment]
That solved it. Thanks much.
