### ISSUE TITLE
orientationDidChange not triggered on Android when device is idle

### ISSUE THREAD

**Issue by garlab** [yamill/react-native-orientation#92]
I have a function orientationDidChange:

```
Orientation.addOrientationListener(this.orientationDidChange);
```

When viewing the screen in landscape, due to inactivity my screen locked. Picking up the phone, I moved it to portrait and unlocked the screen. The screen was then displayed with the landscape view.

Checking showed that orientationDidChange is not triggered when doing landscape -> locking -> portrait -> unlocking, but it is when doing portrait -> locking -> landscape -> unlocking.

I am using for my tests a Samsung Galaxy S6 with Android 6.0.1 and react-native-orientation@1.17.0

**Comment by Jaessun** [comment]
I know this issue is a bit old but as I had the same problem I thought I'd share the solution I found.

If you use react native's [`AppState`](https://facebook.github.io/react-native/docs/appstate.html), you can listen to changes in the application's state with `AppState.addEventListener`. This will tell when the application goes in the background and comes back to the foreground. 

In the listener you can then use `Orientation.getOrientation` to get the device orientation when the application becomes active and update your screen accordingly.

**Comment by colinramsay** [comment]
@Jaessun that seems like a reasonable solution (thanks!), I wouldn't expect orientation events to fire when the app is idle. @garlab I'm going to close this issue as it seems like the method @Jaessun  has suggested will work. Please let us know if that's not the case and we'll re-open.
